name: "Artemis Project CI"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build Frontend
        run: npm run build --prefix client
