name: "Artemis Project CI"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ["8.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from github Action
        uses: supercharge/mongodb-github-action@v1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          #   MONGO_URL: ${{ secrets.MONGO_URL}}
          MONGO_URL: mongodb://localhost:27017/nasa
        run: npm test
      - name: Build Frontend
        run: npm run build --prefix client
